import { Geist, Geist_Mono, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import UserProvider from "@/contexts/UserContext";
import { Toaster } from "sonner";
import ThemeProvider from "@/contexts/ThemeContext";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "PromptEdu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <head>
          <link rel="icon" href="/faavicon.png" />
        </head>
        <body className={kumbhSans.className}>
          <ThemeProvider>
            <UserProvider>{children}</UserProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
